const actionTypes = Object.freeze({
  COMPLETE: "COMPLETE",
  ERROR: "ERROR",
  FAIL: "FAIL",
  GOOD: "GOOD",
  INCOMPLETE: "INCOMPLETE",
  WARN: "WARN",
  CREATE_REQUESTS: "CREATE_REQUESTS",
  ENQUEUE_REQUEST: "ENQUEUE_REQUEST",
  CANCEL_REQUEST: "CANCEL_REQUEST",
  CANCEL_BATCH: "CANCEL_BATCH",
  BEGIN_REQUEST: "BEGIN_REQUEST",
  START_REQUEST: "START_REQUEST",
  COMPLETE_REQUEST: "COMPLETE_REQUEST",
  COMPLETE_BATCH: "COMPLETE_BATCH",
  CREATE_CR: "CREATE_CHANNEL_REQUEST",
  BATCH_RESOLVED: "BATCH_RESOLVED"
});

export default actionTypes;
