const actionTypes = Object.freeze({
  BEGIN_REQUEST: "BEGIN_REQUEST",

  CANCEL_BATCH: "CANCEL_BATCH",
  CANCEL_REQUEST: "CANCEL_REQUEST",
  CLEAR_REQUESTS: "CLEAR_REQUESTS",

  COMPLETE_BATCH: "COMPLETE_BATCH",
  COMPLETE_REQUEST: "COMPLETE_REQUEST",

  CREATE_CHANNEL: "CREATE_CHANNEL",
  CREATE_REQUESTS: "CREATE_REQUESTS",

  ENQUEUE_REQUEST: "ENQUEUE_REQUEST",

  ERROR: "ERROR",
  FAIL: "FAIL",
  GOOD: "GOOD",
  PAUSE: "PAUSE",
  INCOMPLETE: "INCOMPLETE",

  START_AGAIN: "START_AGAIN",
  START_REQUEST: "START_REQUEST",

  WARN: "WARN"
});

export default actionTypes;
